
gnbsim:
  docker:
    container:
      image: docker.io/isilincoln/gnbsim:demo
      prefix: gnbsim-lincoln
      count: 1
    network:
      macvlan:
        name: gnbnet

  router:
    mcavlan:
      iface: gnbaccess
      subnet_prefix: "172.20"
